### ISSUE TITLE
Failure with WHOIAM.md

### ISSUE THREAD

**Issue by patrickkatzer** [se2p/ps-wise-2021-program-description#1]
I am not sure, if this is the correct place to post this.

In the description on StudIP it is explained, that we have to add a file called "WHOIAM.md". 
But the test if you push your code is, if the file "WHOAMI.md" exists.

**Comment by alessiogambi** [comment]
@patrickkatzer as discussed during the exercise session the correct file name is `WHOAMI.md`.
