### ISSUE TITLE
Uncovering a square is transitive?

### ISSUE THREAD

**Issue by Wooza** [se2p/ps-wise-2021-program-description#10]
When uncovering a square that does not contain a mine, the description states that
> All the adjacent covered squares are automatically uncovered if they are empty.

Where the adjacent squares are defined by 
> the squares adjacent above, below, left, right, and all four diagonals.

When we look at the example `Simple game (win case)`,
we see that by revealing the top left `(1,1)` square, we reveal not only the directly adjacent neighbors `{(1,2), (2,1), (2,2)}`, but also their transitive neighbors.

I think the following statement from the description given [here](http://www.freeminesweeper.org/help/minehelpinstructions.html) is missing:
> If you open a square with 0 neighboring bombs, all its neighbors will automatically open. This can cause a large area to automatically open.

Is this assessment correct or do we apply other rules in our implementation?

**Comment by alessiogambi** [comment]
@Wooza Yes, uncovering the squares is transitive. The process continues until a fixed point is reached.

**Comment by Wooza** [comment]
Okay, thanks for the clarification. I have already used a fix point algorithm in my implementation.
I will create a PR to reflect this somewhere in the description.

**Comment by alessiogambi** [comment]
The description says: `**covered** squares are automatically uncovered if they are empty. ", but I'll push a clarification in a second.
