### ISSUE TITLE
Remove Flags

### ISSUE THREAD

**Issue by patrickkatzer** [se2p/ps-wise-2021-program-description#2]
What happens if a user flags every field? Shouldn't there be the possibilty to remove flags? So, for example, if you added a Flag with "2 2 F", you can remove it again with "2 2 F". 

Or maybe a limit, that you can only have the same number of flags as bombs in the game.

**Comment by alessiogambi** [comment]
@patrickkatzer Let's wait to see how [this issue evolves in the forum](https://studip.uni-passau.de/studip/plugins.php/coreforum/index/index/de339f29b5f4cec937340923125d41e3?cid=bef9f90582acaed67ccbf9c32768561a#de339f29b5f4cec937340923125d41e3) and then decide how to proceed.

**Comment by alessiogambi** [comment]
Conclusion is:
- The `F` action toggles the flag symbol on covered squares.
- There is no pre-defined limit on the number of flags that can be used.
