### ISSUE TITLE
Clarification: Exit codes

### ISSUE THREAD

**Issue by lechlm** [se2p/ps-wise-2021-program-description#20]
- What should happen if the program gets more then one input, so another parameter besides the board configuration file name? I suggest to treat this like a missing file, so exit with code 1 in this case.
- What should happen if the file reader raises an IOException? My suggestion in this case is to exit with code 2, so treat it as an invalid file.

**Comment by Wooza** [comment]
I think both suggestions make sense here.

**Comment by alessiogambi** [comment]
Hi. @lechlm Good points!

To make things easy, I would say that in case multiple parameters are passed to Minesweeper, it can simply consider the first one while ignoring all the remaining ones.

For the second case, this might be some sort of corrupted file or something? In this case, I agree we can use exit code 2 to indicate that the input is not valid.

What do you think?

**Comment by lechlm** [comment]
Exactly, the second case comes up because of the IOException thrown by the read methods of the BufferedReader. I would agree to the suggested solution, sounds good!

**Comment by alessiogambi** [comment]
In this case can you create a pull request and corresponding tests? Since you need to trigger and exception I suggest you use mocks, the system junit rules, and do not execute the program in a separate jvm

**Comment by fatadel** [comment]
@alessiogambi 
In case multiple arguments are passed, the program will consider the **last one**, not the first one, if we use the code mentioned [here](https://github.com/se2p/ps-wise-2021-program-description/issues/14#issuecomment-727584364).

**Comment by alessiogambi** [comment]
Well. I would say that here we are setting the specifications so if we decided that the first argument matters, then the code in other issue will need to be updated. So I suggest we move with our idea to consider the first argument.

**Comment by fatadel** [comment]
@alessiogambi 
Okay, then in case of javascript that would be the third argument, not first, because:
process.argv[0] = path to node executable;
process.argv[1] = path to entry point script;
process.argv[2] = first argument.

**Comment by alessiogambi** [comment]
correct

**Comment by alessiogambi** [comment]
Can I close this issue? It seems that both points have been addressed...

**Comment by lechlm** [comment]
Before closing the issue, I have three remarks/points:

1. According to the program description, config file names including spaces are allowed. Can we assume that such a name is passed to Minesweeper with double quotes or escaped spaces and that possible double quotes inside the name are escaped? Because otherwise we would have more than one input parameter to the program in this case.
2. I tried to create a test for testing the IOException using PowerMock. This requires to specify the classes under test using the annotation PrepareForTest, otherwise whenNew() doesn't work. However, since the Minesweeper class is in another class path, I do not know, how to handle this because I cannot use the URLClassLoader or something. Do you or anybody else have any suggestions?
3. Just to clarify your comment above: Do you want me to create a pull request only for the test or also for updating the program description?

**Comment by alessiogambi** [comment]
Let me try to address those points:

1. I would avoid filenames with spaces, so we can simplify this part on validating the inputs and focus more on the core logic of the assignment. So, in short, we will not create tests that use spaces in the name of the file. I suggest that we also refrain from using paths that contain spaces. 
2. This might be harder than we expect. One possibility to implement this specific test is to mock `System.exit` using [system JUnit rules](https://stefanbirkner.github.io/system-rules/) so we can run MineSweeper in the same JVM of the tests, and at that point, there might be the possibility to inject the exception. If possible, I would not use PowerMock.
3. If you think that both public tests and program description need an update, please create two pull requests.

**Comment by lechlm** [comment]
Thank you for the quick response. I will try to implement such a test in the suggested way. I have also created a pull request to integrate the changes resulting from this issue. Since the implementation of the test is not really related to this issue (because it's a program description issue), I think this issue could be closed.

**Comment by fatadel** [comment]
@alessiogambi 
There is no explicit way for checking for corrupted files in javascript.
The `fs.readFile` or `fs.readFileSync` method can only throw errors with code `ENOENT`, which simply means the file does not exist.
In all the other cases, it will read at least something.
I propose we don't check for corrupted files in javascript as it is not the main goal of the assignment and would involve much more effort and irrelevant code.
What do you think?

**Comment by alessiogambi** [comment]
I agree. The main point of the assignments and the class is not to check files or inputs at this level of details. So we can assume that files are never corrupted.
