### ISSUE TITLE
Priority of config exceptions

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-program-description#25]
If a config file is both - **have an invalid name** and the file **does not exist** - what should the return code be - 1 or 2?
1 - because the file is missing.
2 - because the filename is invalid.

But what are the priorities?

**Comment by alessiogambi** [comment]
@fatadel This should have been addressed by one of the latest changes. Can you confirm this reads ok?

> **Filename has priority over file exists**. Minesweeper should check the validity of the input parameter (as String) even before checking the existence of the file and validating its content. So if an invalid filename is provided, no matter whether the file exists on not, the exit code is `2` (invalid file) and not exit code `1` (missing file)

**Comment by fatadel** [comment]
I confirm 👍
