### ISSUE TITLE
Revealing cells when lost

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-program-description#26]
Did I understand it right that when the game is lost - **all the mines** must be revealed, even those which are flagged?
And also, all the other cells **should stay in their states**.

**Comment by alessiogambi** [comment]
Yes, all the mines should be revealed. But maybe we need to clarify what to do with the other squares? The answer is we leave them as they are. So we reveal the mines only. Also, there's no special highlighting to identify the mine that was triggered and caused the game to be lost.
