### ISSUE TITLE
Board Generation Public Test Ideas

### ISSUE THREAD

**Issue by patrickkatzer** [se2p/ps-wise-2021-program-description#3]
Some ideas to test the generation of the board:

- No file available -> Exit with code 1?
- File contains characters other than * and . -> Exit with code 2
- Length of lines and length of colums are not the same (Board is not rectangular) -> Exit with code 2

**Comment by alessiogambi** [comment]
@patrickkatzer they look promising, please go on and implement them! 😃

**Comment by alessiogambi** [comment]
I close this issue since there are public tests that implement your suggestion.
