### ISSUE TITLE
Remark regarding the "Simple Game (lost case)" example

### ISSUE THREAD

**Issue by lechlm** [se2p/ps-wise-2021-program-description#31]
I'm a little bit confused about this line:

After playing as first move 1 1 R, the game computes following board (note that the console is not shown:

Why shouldn't the console be shown in this case? Since the game is not lost after the first move (1 1 R), the console should be shown. The following sentence also states that a second move (1 3 R) is executed.

**Comment by alessiogambi** [comment]
@lechlm The note refers to the example: in the example reported, the console symbol (`>`) is not shown.
