### ISSUE TITLE
Won Game - Status of Mine fields

### ISSUE THREAD

**Issue by UzunerH** [se2p/ps-wise-2021-program-description#32]
Hi,

I think there is only a specification what should happen if the game is lost (display all mines).

> End of the Game
A game ends when the player uncover all non-mine squares (win) or a mine is detonated (lost). Flagging all the mined squares is not required to finish the game; however, when the game is lost all the mines must be clearly shown on the board.

But what happens with the remaining fields (which are obviously all mines), when the game is won. Are they to be left as is (some may be flagged by player, some may be not), or should all be revealed or shown covered or shown as flag(which is I think the canonical way as I remember playing minesweeper in the past).
The only reference regarding this in the program description is this board configuration, which handles the situtation as: Show the remaining fields as is. (Theoretically it could also be "make all remianing fields standard covered")

```
┌───┬───┬───┐[\n]
│ ▓ │ 1 │   │[\n]
├───┼───┼───┤[\n]
│ ▓ │ 1 │ 1 │[\n]
├───┼───┼───┤[\n]
│ ▓ │ ▓ │ ▓ │[\n]
└───┴───┴───┘[\n]
╔═══════════╗[\n]
║You Won!   ║[\n]
╚═══════════╝[\n]
```

Since this point is not specifically addressed, I thought I mention it to be sure...

**Comment by alessiogambi** [comment]
@UzunerH if the game is won the game should simply show the state resulting from the last move. No additional flagging, revealing or anything else has to be done on the board. If this comment addresses your question, please close the issue, otherwise elaborate the issue a bit more.
