### ISSUE TITLE
Misleading sentence

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-program-description#34]
> After left-clicking a square, all its "neighbors" covered squares are automatically uncovered if they are empty. 

This sentence is misleading because the empty neighbours are uncovered only in case **an empty cell** was left-clicked.
So, in case a numbered cell was left-clicked it doesn't reveal its neighbours.
At least this is what is understood after reading the description further, and this is the behaviour of the "usual" Minesweeper game.

@alessiogambi, am I right here?

**Comment by alessiogambi** [comment]
Yes, this reads a bit misleading and I'll update the description to further clarify it. Note that few lines below you the description reads:

>> NOTE: If the player uncovers a square with 0 neighboring bombs, all its neighbors will be automatically uncovered. This may cause a large area to automatically open, and in some cases to win the game after a single move.
