### ISSUE TITLE
Package name `default` is not allowed

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-program-description#36]
I have been struggling with the package structure for the Java implementation when I eventually found that the error lies in the initial project structure.
It is not allowed to name packages with reserved names and `default` is a reserved name.
See this SO question for details - https://stackoverflow.com/questions/51610038/why-cannot-name-a-java-package-default.

So, we probably should change the project structure and, apparently, the makefiles as well.

**Comment by fatadel** [comment]
I propose we rename the packages as follows:
`default` -> `default-plugin`
`fancy` -> `fancy-plugin`

**Comment by fatadel** [comment]
Ideally, what would be cool is to wrap all minesweeper related files to a package as well.
Then we could benefit from the packaging practices mentioned in the slides (see below).

<img width="894" alt="image" src="https://user-images.githubusercontent.com/14371560/105089094-fcf14380-5a9c-11eb-8dd4-8754cc29f4e6.png">

**Comment by fatadel** [comment]
Ideally, what would be cool is to pack all minesweeper related files into a package as well.
Then we could benefit from the packaging practices mentioned in the slides (see below).
Currently, the assumption is that `Minesweeper.java` lies inside `java` folder and cannot be moved to a package.

So, I propose the following structure for the Java implementation:

`root` -> `java` -> `minesweeper` (package) -> `Minesweeper.java` 

<img width="894" alt="image" src="https://user-images.githubusercontent.com/14371560/105089094-fcf14380-5a9c-11eb-8dd4-8754cc29f4e6.png">

**Comment by fatadel** [comment]
Ideally, what would be cool is to pack all minesweeper related files into a package as well.
Then we could benefit from the packaging practices mentioned in the slides (see below).
Currently, the assumption is that `Minesweeper.java` lies inside `java` folder and cannot be moved into a package.

So, I propose the following structure for the Java implementation:

`root` -> `java` -> `minesweeper` (package) -> `Minesweeper.java` 

<img width="894" alt="image" src="https://user-images.githubusercontent.com/14371560/105089094-fcf14380-5a9c-11eb-8dd4-8754cc29f4e6.png">

**Comment by fatadel** [comment]
@alessiogambi

**Comment by manuel43** [comment]
For me the given structure works fine. Yes it is not allowed to have "default" in your package structure but in my implementation this is not necessary. The make files take care that the jar-files are built (there you need no package-structure). Your program loads this jar-files and makes them available for the class loader without any package-structure.

Maybe this helps you a little bit.

**Comment by alessiogambi** [comment]
@fatadel @manuel43 is right. That is the intended use of the make files. However you should be able to declare packages inside the plugins folder (of course without using keywords like default) and the make files should work out of the box.

Just a clarification. In the slides packaging does not necessarily mean to use Java packages. For example we can package the code in jars without even using Java packages

**Comment by fatadel** [comment]
@alessiogambi @manuel43 thank you very much for your responses and advice.

I always try to minimize errors/warnings in my code. And for the initial project structure, IDEA gives an error of missing package declaration within `DefaultPlugin` and `FancyPlugin` classes (even if everything works fine). That's the reason I was trying to add package declarations.

**Comment by alessiogambi** [comment]
The IDE is right. Using the default package in Java is not a best practice but it is simple and for our needs was enough. Glad we solved.
