### ISSUE TITLE
Config file name

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-program-description#5]
If the name of a config file is just `.cfg`, should it be accepted or not?
I will also add a test case for this when it will be clarified (as I've noticed there is no this kind of a test).

**Comment by alessiogambi** [comment]
@fatadel As we discussed in the exercise session, `.cfg` is NOT a valid name. We consider this as an invalid input case (if such a file exists!), and the system should exit with exit code `2`.

**Comment by alessiogambi** [comment]
@fatadel Please remember to commit some test cases

**Comment by fatadel** [comment]
@alessiogambi I don't think it's a good idea to add a new test before resolving #14, so I will postpone the new tests until the issue is resolved.

**Comment by alessiogambi** [comment]
Well, you can start contributing test cases for java (I saw some tests checking properties of the input file) and proposing a fix for #14
